#pragma once

#if LANGUAGE == FRENCH
#define T_N "N"
#define T_S "S"
#define T_E "E"
#define T_W "O"

#define T_PRESS_KEY "App. sur boutton"
#define T_TO_REBOOT "pour redemarrer"
#define T_WILL_REBOOT "va redemarrer"
#define T_DEVICE "Dispositif"
#define T_TELESCOPE "Télescope"
#define T_FOCUSER "Focuser"
#define T_MOUNT "Monture"
#define T_MOUNTTYPE "Type de Monture"

#define T_LIMITS "Limites"
#define T_NOT_CONNECTED "pas Connecté"
#define T_TUNKOWN "Inconnue"
#define T_ERROR "ERREUR"
#define T_WARNING "ALERTE"
#define T_STAR "Etoile"
#define T_SLEWINGTO "Pointe vers" 
#define T_RECENTER "Recentre"
#define T_SELECTASTAR "Select. une Etoile"
#define T_FROMFOLLOWINGLIST "de la liste"
#define T_SELECTION "Selection"
#define T_ABORTED "Abandonné"
#define T_ALIGNMENT "Alignement"
#define T_FAILED "Echoué"
#define T_HASFAILED "a échoué"

#define T_GUIDERATE "Vit. Guidage"
#define T_MAXRATE "Vit. Max"
#define T_STARTED "Démarré"
#define T_STOP "Arret"
#define T_CANCEL "Annule"
#define T_CANCELED "Annulé"
#define T_WRONG "Mauvais"
#define T_NOTDEFINED "non defini"
#define T_SUCESS "Réussi"
#define T_STARADDED "Étoile ajouté"
#define T_VERSION "version"
#define T_YES "OUI"
#define T_NO "NON"
#define T_ON "ON"
#define T_OFF "OFF"
#define T_RESET "Reset"
#define T_VALUE "Valeur"
#define T_SET "Envoyée"
#define T_GET "Recue"
#define T_DONE "fait"
#define T_TO "à"
#define T_LOW "Faible"
#define T_HIGH "Haut"
#define T_MIN "Min"
#define T_MAX "Max"
#define T_FACTORY "Usine"
#define T_DIRECT "Directe"
#define T_REVERSE "Inverse"
#define T_REVERSEDROTATION "Rotation Inversée"
#define T_DIRECTROTATION "Rotation Directe"
#define T_CONFIG "Config"
#define T_ROTATION "Rotation"
#define T_BACKLASH "Jeu"
#define T_GEAR "Reducteur"
#define T_RATIO "Reduction"
#define T_MICROSTEP "Micropas"
#define T_INSECONDS "en secondes"
#define T_MOTOR "Moteur"
#define T_STEPPER "Mt pp"
#define T_STEPS "Pas"
#define T_RESOLUTION "Résolution"
#define T_INCREMENTATION "Increment"
#define T_STEPSPERROT "Pas par Rot."
#define T_LOWCURR "Amp. Bas"
#define T_HIGHCURR "Amp. Haut"
#define T_CURRENT "Amperage"
#define T_PEAK "Pic"
#define T_MaxSlew "Vitesse Max"
#define T_Config "Config"
#define T_TIMESETTINGS "Param. Temps"
#define T_TELESCOPESETTINGS "Param. Telescope"
#define T_SHCSETTINGS "Param. SHC"
#define T_SLEWSETTING "Param. Pointage"
#define T_MOTORSETTINGS "Param.  Moteur %u"
#define T_SHOWSETTINGS "Affiche Parametres"
#define T_FOCUSERSETTINGS "Param. Focuser"
#define T_DISPLAYSETTINGS "Param Écran"

#define T_ACCELERATION "Acceleration"

#define T_LATITUDE "Latitude"
#define T_LONGITUDE "Longitude"
#define T_AZIMUTH "Azimut"
#define T_ALTITUDE "Altitude"
#define T_DECLINAISON "Declinaison"
#define T_RIGHTASC "Asc. Droite"
#define T_LOCALTIME "Heure Civile"

#define T_PARKPOSITION "Position Park"
#define T_MAXPOSITION "Position Max"
#define T_MAXPOSITION2 "Pos. Max"
#define T_STARTPOSITION2 "Pos. Démar."

#define T_PARKPOSITION "Park Position"
#define T_GOTOPOSITION "Goto Position"
#define T_SYNCPOSITION "Sync Position"
#define T_MANUALSPEED "Manual Speed"
#define T_MANUALSPEED2 "Man. Speed"
#define T_GOTOSPEED "Goto Speed"
#define T_GOTOSPEED2 "Goto Speed"
#define T_ACCFORMAN "Acc. for Man."
#define T_ACCFORMAN2 "Acc. man."
#define T_ACCFORGOTO "Acc. for Goto"
#define T_ACCFORGOTO2 "Acc. cmd."
#define T_DECFORMAN "Dec. for Man."
#define T_DECFORMAN2 "Dec. man."

#define T_UNPARK "Dégare"
#define T_PARK "Gare"
#define T_HOME "Maison"
#define T_PARKED "Garé"
#define T_NOOBJECT "Pas d'Objet"
#define T_SELECTED "Selectionné"
#define T_FOCUSERACTION "Action Focuser"

#define T_SETPARK "Def. Park"
#define T_ATHOME "à la maison"
#define T_UNLOCK "Unlock"
#define T_LOCK "Lock"
#define T_GOTO "Goto"
#define T_POSITION "Position"

#define T_SYNC "Sync"
#define T_SYNCED "Synced"
#define T_HOUR "Hour"
#define T_SYNCEDAT "Synced at"
#define T_ALIGN "Align"
#define T_TRACKING "Tracking"
#define T_STARTTRAKING "Start Tracking"
#define T_STOPTRAKING "Stop Tracking"
#define T_TRAKINGSTATE "Tracking State"
#define T_SIDEOFPIER "Side of Pier"
#define T_SAVE "Save"
#define T_SAVED "Saved"
#define T_Clear "Clear"
#define T_SPIRAL "Spiral"
#define T_LX200COMMAND "LX200 Command"
#define T_SETVEALUE "Set Value"
#define T_GETVEALUE "Get Value"
#define T_SETTARGET "Set Target"
#define T_TARGET "Target"
#define T_TARGETIS "Target is"
#define T_TELESCOPEIS "Telescope is"
#define T_TELESCOPEEXCEED "Telescope exceed"
#define T_SENSORLIMIT "Sensor limit"
#define T_DECLIMIT "DEC limit"
#define T_AZMLIMIT "AZM limit"
#define T_BELOWHORIZON "Below Horizon"
#define T_TELESCOPEMOTOR "Telescope Motor"
#define T_OUTSIDELIMITS "Outside Limits"
#define T_FAULT "Fault"
#define T_BUSY "Busy"
#define T_CANTPARK "Can't Park"
#define T_CANTGOHOME "Can't go Home"

#define T_TELESCOPEACTION "Telescope Action"
#define T_SETSPEED "Set Speed"
#define T_SIDEREAL "Sidereal"
#define T_TIME "Time"
#define T_SITE "Site"
#define T_SYNCWITHGNSS "Sync with GNSS"
#define T_LUNAR "Lunar"
#define T_SOLAR "Solar"
#define T_CLOCK "Clock"
#define T_TIMEZONE "Time Zone"
#define T_DATE "Date"
#define T_GNSSTIME "GNSS Time"
#define T_NOGNSS "NO GNSS"
#define T_SIGNAL "Signal"
#define T_DISPLAY "Display"
#define T_BUTTONSPEED "Button Speed"

#define T_CONTRAST "Contrast"
#define T_TURNOFF "Turn Off"
#define T_SLEEP "Sleep"
#define T_DEEPSLEEP "DeepSleep"
#define T_PRESSSHIFTKEY "Press Shift Key"
#define T_TOTURNON "to turn on"
#define T_AFTER "after"
#define T_LOWCONTRAST "Low Contrast"
#define T_TURNDISPLAYOFF "Turn display off"


#define T_BUTTONSPEED "Button Speed"
#define T_SLOW "Slow"
#define T_MEDIUM "Medium"
#define T_FAST "Fast"

#define T_SITEELEVATION "Site Elevation"
#define T_HORIZON "Horizon"
#define T_HORIZONLIMIT "Horizon Limit"
#define T_OVERHEAD "Overhead"
#define T_OVERHEADLIMIT "Overhead Limit"
#define T_MERIDIANE "Meridian E"
#define T_MERIDIANW "Meridian W"
#define T_MERIDIANLIMIT "Meridian Limit"
#define T_MERIDIANLIMITE "Meridian Limit E"
#define T_MERIDIANLIMITW "Meridian Limit W"

#define T_MAXHOURANGLE "Max Hour Angle"
#define T_UNDERPOLE "Under Pole"
#define T_UNDERPOLELIMIT "Under Pole Limit"

#define T_CURRENTLYTRACKING "currently Tracking"
#define T_CANNOTBECHANGED "cannot be changed"
#define T_INITIALISATION "Initilisation"
#define T_THEMOUNTMUSTBEATHOME1 "The mount must"
#define T_THEMOUNTMUSTBEATHOME2 "be set at"
#define T_THEMOUNTMUSTBEATHOME3 "home position."
#define T_READYFOR "Ready for"
#define T_MOUNTSYNCED "Mount Synced"
#define T_HANDCONTROLLER "Hand Controller"
#define T_MAINUNITINFO "Main Unit Info"
#define T_SHOWVERSION "Show Version"
#define T_REBOOT "Reboot"
#define T_RESETTOFACTORY "Reset to Factory"
#define T_FIRMWAREVERSION "Firmware Version"
#define T_GERMANEQUATORIAL "German Equatorial"
#define T_EQUATORIALFORK "Equatorial Fork"
#define T_ALTAAZIMUTAL "Altazimutal"
#define T_ALTAAZIMUTALFORK "Altazimutal Fork"

#define T_TURNWIFIOFF "Turn Wifi off"
#define T_TURNWIFION "Turn Wifi on"
#define T_SHOWPASSWORD "Show Password"
#define T_SELECTMODE "Select Mode"
#define T_SHOWIP "Show IP"
#define T_PASSWORDIS "Password is"
#define T_ACCESPOINT "AccesPoint"
#define T_WIFIINTERFACE "Wifi Interface"
#endif