#pragma once

#define T_N "N"
#define T_S "S"
#define T_E "O"
#define T_W "W"

#define T_NORTH "Nord"
#define T_SOUTH "Süd"
#define T_EAST "Ost"
#define T_WEST "West"

#define T_PRESS_KEY "Taste drücken"
#define T_TO_REBOOT "für Neustart"
#define T_WILL_REBOOT "Starte neu"
#define T_DEVICE "Gerät"
#define T_TELESCOPE "Teleskop"
#define T_FOCUSER "Fokusierer"
#define T_MOUNT "Montierung"
#define T_MOUNTTYPE "Montierungsart"

#define T_LIMITS "Grenzen"
#define T_NOT_CONNECTED "Nicht verbunden"
#define T_TUNKOWN "Unbekannt"
#define T_ERROR "FEHLER"
#define T_WARNING "WARNUNG"
#define T_STAR "Stern"
#define T_SLEWINGTO "Fahre zu"
#define T_RECENTER "Neuzentrieren"
#define T_SELECTASTAR "Einen Stern auswählen"
#define T_FROMFOLLOWINGLIST "Aus der folgenden Liste"
#define T_SELECTION "Auswahl"
#define T_ABORTED "Abgebrochen"
#define T_ALIGNMENT "Ausrichtung"
#define T_FAILED "Fehlgeschlagen"
#define T_HASFAILED "ist fehlgeschlagen"

#define T_GUIDERATE "GuidingGeschw."
#define T_MAXRATE "Max Geschw."
#define T_STARTED "Gestartet"
#define T_STOP "Stop"
#define T_CANCEL "Abbruch"
#define T_CANCELED "Abgebrochen"
#define T_WRONG "Falsch"
#define T_NOTDEFINED "nicht definiert"
#define T_SUCESS "Erfolg"
#define T_STARADDED "Stern hinzugefügt"
#define T_VERSION "Version"
#define T_YES "Ja"
#define T_NO "Nein"
#define T_ON "AN"
#define T_OFF "AUS"
#define T_RESET "Grundstellung"
#define T_VALUE "Wert"
#define T_SET "Setzen"
#define T_GET "Erhalten"
#define T_DONE "Erledigt"
#define T_TO "zu"
#define T_LOW "Niedrig"
#define T_HIGH "Hoch"
#define T_MIN "Min"
#define T_MAX "Max"
#define T_FACTORY "Werk"
#define T_DIRECT "Direkt"
#define T_REVERSE "Rückwärtig"
#define T_REVERSEDROTATION "Rückwärtige Drehung"
#define T_DIRECTROTATION "Direkte Drehung"
#define T_CONFIG "Konfiguration"
#define T_ROTATION "Drehung"
#define T_BACKLASH "Getriebespiel"
#define T_GEAR "Getriebezahl"
#define T_RATIO "Verhältnis"
#define T_MICROSTEP "Mikroschritt"
#define T_INSECONDS "in Sekunden"
#define T_MOTOR "Motor"
#define T_STEPPER "Stepper"
#define T_STEPS "Schritte"
#define T_RESOLUTION "Auflösung"
#define T_INCREMENTATION "Schrittweitenparameter"
#define T_STEPSPERROT "Schritte pro Rotation"
#define T_LOWCURR "niedrige Stromstärke"
#define T_HIGHCURR "hohe Stromstärke"
#define T_CURRENT "Strom"
#define T_PEAK "Spitze"
#define T_MaxSlew "Max. Schwenk"
#define T_Config "Konfiguration"
#define T_TIMESETTINGS "Zeiteinstellungen"
#define T_TELESCOPESETTINGS "Teleskopeinstellungen"
#define T_SHCSETTINGS "SHC Einstellungen"
#define T_SLEWSETTING "Schwenk Einstellungen"
#define T_MOTORSETTINGS "Motor %u Einstellungen"
#define T_SHOWSETTINGS "Zeige Einstellungen"
#define T_FOCUSERSETTINGS "Fokusierer Einstellungen"
#define T_DISPLAYSETTINGS "Anzeige Einstellungen"

#define T_ACCELERATION "Beschleunigung"

#define T_LATITUDE "Breitengrad"
#define T_LONGITUDE "Längengrade"
#define T_AZIMUTH "Azimut"
#define T_ALTITUDE "Höhe"
#define T_DECLINAISON "Deklination"
#define T_RIGHTASC "Rektaszension"
#define T_LOCALTIME "Lokale Zeit"
#define T_DEGREE "grad"

#define T_PARKPOSITION "Park Position"
#define T_MAXPOSITION "Max Position"
#define T_MAXPOSITION2 "Max  Pos."
#define T_STARTPOSITION2 "Start Pos."

#define T_PARKPOSITION "Park Position"
#define T_GOTOPOSITION "Goto Position"
#define T_SYNCPOSITION "Sync Position"
#define T_MANUALSPEED "Manuelle Geschw."
#define T_MANUALSPEED2 "Man. Geschw."
#define T_GOTOSPEED "Goto Geschw."
#define T_GOTOSPEED2 "Goto Geschw."
#define T_ACCFORMAN "Beschl. für Man."
#define T_ACCFORMAN2 "Beschl. manuell"
#define T_ACCFORGOTO "Beschl. für Goto"
#define T_ACCFORGOTO2 "Beschl. cmd."
#define T_DECFORMAN "Dek. für Man."
#define T_DECFORMAN2 "Dek. manuell"

#define T_UNPARK "Unpark"
#define T_PARK "Park"
#define T_HOME "Home"
#define T_PARKED "Geparkt"
#define T_NOOBJECT "Kein Objekt"
#define T_SELECTED "Ausgewählt"
#define T_FOCUSERACTION "Fokusierer Aktion"

#define T_SETPARK "Setze Parkposition"
#define T_ATHOME "at Home"
#define T_UNLOCK "Entsperren"
#define T_LOCK "Sperre"
#define T_GOTO "Goto"
#define T_POSITION "Position"

#define T_SYNC "Synchronisierung"
#define T_SYNCED "Synchronisiert"
#define T_HOUR "Stunde"
#define T_HOURS "Stunden"
#define T_SYNCEDAT "Synchronisiert bei"
#define T_ALIGN "Ausrichten"
#define T_TRACKING "Nachführung"
#define T_STARTTRACKING "Nachführung starten"
#define T_STOPTRACKING "Nachführung stoppen"
#define T_TRACKINGSTATE "Status Nachführung"
#define T_SIDEOFPIER "Seite der Montierung"
#define T_SETSIDEOFPIER "Set Side of Pier
#define T_SAVE "Speichern"
#define T_SAVED "Gespeichert"
#define T_Clear "Löschen"
#define T_SPIRAL "Spiral"
#define T_LX200COMMAND "LX200 Command"
#define T_SETVEALUE "Wert setzen"
#define T_GETVEALUE "Wert auslesen"
#define T_SETTARGET "Ziel setzen"
#define T_TARGET "Ziel/Objekt"
#define T_TARGETIS "Ziel/Objekt ist"
#define T_TELESCOPEIS "Teleskop ist"
#define T_TELESCOPEEXCEED "Teleskop überschritten"
#define T_SENSORLIMIT "Sensorgrenze"
#define T_DECLIMIT "DEK Grenze"
#define T_AZMLIMIT "AZM Grenze"
#define T_BELOWHORIZON "Unter dem Horizont"
#define T_TELESCOPEMOTOR "Teleskopmotor"
#define T_OUTSIDELIMITS "Ausserhalb der Grenzen"
#define T_FAULT "Fault"
#define T_BUSY "Busy"
#define T_CANTPARK "Parken nicht möglich"
#define T_CANTGOHOME "Home nicht möglich"

#define T_TELESCOPEACTION "Teleskop Aktion"
#define T_SETSPEED "Geschw. setzen"
#define T_SIDEREAL "Stern"
#define T_TIME "Zeit"
#define T_SITE "Ort"
#define T_SYNCWITHGNSS "Sync mit GNSS"
#define T_LUNAR "Mond"
#define T_SOLAR "Sonne"
#define T_CLOCK "Uhr"
#define T_TIMEZONE "Zeitzone"
#define T_DATE "Datum"
#define T_GNSSTIME "GNSS Zeit"
#define T_NOGNSS "KEIN GNSS"
#define T_SIGNAL "Signal"
#define T_DISPLAY "Anzeige"
#define T_BUTTONSPEED "Geschw. Knopf"

#define T_CONTRAST "Kontrast"
#define T_TURNOFF "Ausschalten"
#define T_SLEEP "Schlaf"
#define T_DEEPSLEEP "Tiefer Schlaf"
#define T_PRESSSHIFTKEY "Shift-Taste drücken"
#define T_TOTURNON "zum Anschalten"
#define T_AFTER "danach"
#define T_LOWCONTRAST "Niedriger Kontrast"
#define T_TURNDISPLAYOFF "Anzeige ausschalten"


#define T_BUTTONSPEED "Geschw. Knopf"
#define T_SLOW "Langsam"
#define T_MEDIUM "Mittel"
#define T_FAST "Schnell"

#define T_SITEELEVATION "geo. Höhe"
#define T_HORIZON "Horizont"
#define T_HORIZONLIMIT "Horizontgrenze"
#define T_OVERHEAD "Overhead"
#define T_OVERHEADLIMIT "Overhead Limit"
#define T_MERIDIANE "Meridian O"
#define T_MERIDIANW "Meridian W"
#define T_MERIDIANLIMIT "Meridiangrenze"
#define T_MERIDIANLIMITE "Meridiangrenze O"
#define T_MERIDIANLIMITW "Meridiangrenze W"

#define T_MAXHOURANGLE "Max. Stundenwinkel"
#define T_UNDERPOLE "Unter dem Pol"
#define T_UNDERPOLELIMIT "Grenze unter dem Pol"

#define T_CURRENTLYTRACKING "Nachführung läuft"
#define T_CANNOTBECHANGED "kann nicht geändert werden"
#define T_INITIALISATION "Initialisierung"
#define T_THEMOUNTMUSTBEATHOME1 "Die Montierung muss"
#define T_THEMOUNTMUSTBEATHOME2 "auf die Homeposition"
#define T_THEMOUNTMUSTBEATHOME3 "gesetzt werden."
#define T_READYFOR "Bereit für"
#define T_MOUNTSYNCED "Montierung synchronisiert"
#define T_HANDCONTROLLER "Handkontroller"
#define T_MAINUNITINFO "Steuergerät Info"
#define T_SHOWVERSION "Versionsnr. zeigen"
#define T_REBOOT "Neustart"
#define T_RESETTOFACTORY "zurücksetzen auf Werk"
#define T_FIRMWAREVERSION "Firmwareversion"
#define T_GERMANEQUATORIAL "Deutsche Montierung"
#define T_EQUATORIALFORK "Äquatorial Gabel"
#define T_ALTAAZIMUTAL "Alt-Azimutal"
#define T_ALTAAZIMUTALFORK "Alt-Azimutal Gabel"

#define T_TURNWIFIOFF "WLAN ausschalten"
#define T_TURNWIFION "WLAN anschalten"
#define T_SHOWPASSWORD "Passwort anzeigen"
#define T_SELECTMODE "Modus wählen"
#define T_SHOWIP "IP-Adresse zeigen"
#define T_PASSWORDIS "Passwort ist"
#define T_ACCESPOINT "Zugangspunkt"
#define T_WIFIINTERFACE "WLAN Verbindung"

#define T_SUN "Sonne"
#define T_MERCURY "Merkur"
#define T_VENUS "Venus"
#define T_MARS "Mars"
#define T_JUPITER "Jupiter"
#define T_SATURN "Saturn"
#define T_URANUS "Uranus"
#define T_NEPTUNE "Neptun"
#define T_MOON "Mond"

#define T_CATALOGS "Katalogen"
#define T_SOLARSYSTEM "Sonnensystem"
#define T_COORDINATES "Koordinaten"
#define T_USERDEFINED "Benutzer definiert"

#define T_FILTER "Filter"
#define T_FILTERS "Filters"
#define T_ALLOW "Elaub"
#define T_ABOVE "Über"
#define T_DEG "deg."
#define T_ALL "Alle"
#define T_FILTERBYCON "Filter bei Kon"
#define T_FILTERBYTYPE "Filter bei Typ"
#define T_ABOVE_HORIZON "Über Horizont"
