name=TeenAstroCoordConv
version=1.0.0
author=Markus Noga, Charles Lemaire
maintainer=Charles Lemaire
sentence=Two-star alignment library based on the Taki method
paragraph=Computes a 3x3 transformation matrix between sky and instrument coordinates using 2-star alignment, SVD refinement, and optional axis error minimization.
category=Other
url=https://github.com/charleslemaire0/TeenAstro
architectures=*
depends=TeenAstroLA3, svd3
