#pragma once

#define T_N "N"
#define T_S "S"
#define T_E "E"
#define T_W "O"

#define T_NORTH "Nord"
#define T_SOUTH "Sud"
#define T_EAST "Est"
#define T_WEST "Ouest"

#define T_PRESS_KEY "App. sur boutton"
#define T_TO_REBOOT "pour redémarrer"
#define T_WILL_REBOOT "va redémarrer"
#define T_DEVICE "Dispositif"
#define T_TELESCOPE "Télescope"
#define T_FOCUSER "Focuser"
#define T_MOUNT "Monture"
#define T_MOUNTTYPE "Type de Monture"
#define T_SELECT_MOUNT "Sélect. une Monture"
#define T_POLAR_ALIGNMENT "Alignement du Pôle"
#define T_TRUE_POLE "Pôle Vrai"
#define T_APPARENT_POLE "Pôle Apparent"

#define T_ENCODERS "Encodeurs"
#define T_PULSEPERDEGREE "Pulse par deg"
#define T_AUTO_SYNC "Auto Sync"
#define T_CALIBRATION "Calibration"

#define T_LIMITS "Limites"
#define T_CONNECTED "Connecté"
#define T_NOT_CONNECTED "pas Connecté"
#define T_TUNKOWN "Inconnue"
#define T_ERROR "ERREUR"
#define T_WARNING "ALERTE"
#define T_STAR "Étoile"
#define T_STARS "Étoiles"
#define T_SLEWINGTO "Pointe vers" 
#define T_RECENTER "Recentre"
#define T_SELECTASTAR "Sélect. une Étoile"
#define T_FROMFOLLOWINGLIST "de la liste"
#define T_SELECTION "Sélection"
#define T_ABORTED "Abandonné"
#define T_ALIGNMENT "Alignement"
#define T_FAILED "Echoué"
#define T_HASFAILED "a échoué"

#define T_SPEED "Vitesse"
#define T_GUIDESPEED "Vitesse guidage"
#define T_DEFAULTSPEED "Vitesse standard"
#define T_DRIFTSPEED "Vitesse de derive"
#define T_FASTSPEED "Vitesse rapide"
#define T_MEDIUMSPEED "Vitesse moyenne"
#define T_SLOWSPEED "Vitesse lente"
#define T_MAXSPEED "Vitesse max"
#define T_GUIDE "Guidage"
#define T_FAST "Rapide"
#define T_MEDIUM "Moyenne"
#define T_SLOW "Lente"
#define T_MAX "Max"

#define T_STARTED "Démarrée"
#define T_STOP "Arrêt"
#define T_CANCEL "Annule"
#define T_CANCELED "Annulé"
#define T_COMPLETE "terminé"
#define T_WRONG "Mauvais"
#define T_NOTDEFINED "non défini"
#define T_SUCESS "Réussi"
#define T_STARADDED "Étoile ajoutée"
#define T_VERSION "version"
#define T_YES "OUI"
#define T_NO "NON"
#define T_ON "ON"
#define T_OFF "OFF"
#define T_RESET "Reset"
#define T_VALUE "Valeur"
#define T_SET "Sauvegardé"
#define T_GET "Reçue"
#define T_DONE "Fait"
#define T_TO "à"
#define T_LOW "Faible"
#define T_HIGH "Haut"
#define T_MIN "Min"
#define T_MAX "Max"
#define T_ERGONOMICS "Ergonomie"
#define T_RIGHT_HANDER "Droitier"
#define T_LEFT_HANDER "Gaucher"
#define T_FACTORY "Usine"
#define T_DIRECT "Directe"
#define T_REVERSE "Inversée"
#define T_REVERSEDROTATION "Rotation Inversée"
#define T_DIRECTROTATION "Rotation Directe"
#define T_CONFIG "Config"
#define T_ROTATION "Rotation"
#define T_BACKLASH "Jeu"
#define T_BACKLASHSPEED "Vitesse Jeu"
#define T_GEAR "Réduction"
#define T_RATIO "Rapport"
#define T_MICROSTEP "Micropas"
#define T_INSECONDS "en secondes"
#define T_MOTOR "Moteur"
#define T_STEPPER "Mot. pp"
#define T_STEPS "Pas"
#define T_RESOLUTION "Résolution"
#define T_INCREMENTATION "Incrément"
#define T_STEPSPERROT "Nb. Pas par Rot."
#define T_LOWCURR "Amp. Bas"
#define T_HIGHCURR "Amp. Haut"
#define T_CURRENT "Ampérage"
#define T_PEAK "Pic"
#define T_MaxSlew "Vitesse Max"
#define T_Config "Config"
#define T_TIMESETTINGS "Param. Temps"
#define T_TELESCOPESETTINGS "Param. Télescope"
#define T_SHCSETTINGS "Param. Raquette"
#define T_SLEWSETTING "Param. Pointage"
#define T_MOTORSETTINGS "Param.  Moteur %u"
#define T_SHOWSETTINGS "Afficher Paramètres"
#define T_FOCUSERSETTINGS "Param. Focuser"
#define T_DISPLAYSETTINGS "Param. Écran"
#define T_FOCUSERINFO "Info Focuser"

#define T_ACCELERATION "Accélération"

#define T_LATITUDE "Latitude"
#define T_LONGITUDE "Longitude"
#define T_AZIMUTH "Azimuth"
#define T_ALTITUDE "Altitude"
#define T_DECLINAISON "Déclinaison"
#define T_RIGHTASC "Asc. Droite"
#define T_LOCALTIME "Heure Civile"
#define T_DEGREE "degrés"

#define T_PARKPOSITION "Position Parc"
#define T_MAXPOSITION "Position Max"
#define T_MAXPOSITION2 "Pos. Max"
#define T_STARTPOSITION2 "Pos. Démar."

#define T_GOTOPOSITION "Goto Position"
#define T_SYNCPOSITION "Synchro Position"
#define T_MANUALSPEED "Vitesse Manuel"
#define T_MANUALSPEED2 "Vitesse Man."
#define T_GOTOSPEED "Vitesse Goto"
#define T_GOTOSPEED2 "Vitesse Goto"
#define T_ACCFORMAN "Accél. pour Man."
#define T_ACCFORMAN2 "Accél. man."
#define T_ACCFORGOTO "Accél. pour Goto"
#define T_ACCFORGOTO2 "Accél. cmd."
#define T_DECFORMAN "Dec. pour Man."
#define T_DECFORMAN2 "Dec. man."

#define T_UNPARK "Déparc"
#define T_PARK "Parc"
#define T_FLIP "Retournement"
#define T_HOME "Home"
#define T_PARKED "Parqué"
#define T_NOOBJECT "Pas d'Objet"
#define T_SELECTED "Selectionné"
#define T_FOCUSERACTION "Action M.A.P"

#define T_PARKANDHOME "Parc et Maison"
#define T_SETPARK "Déf. Pos. Parc"
#define T_SETHOME "Déf Pos. Maison"
#define T_RESETHOME "Reset Pos. Maison"

#define T_ATHOME "à la maison"
#define T_UNLOCK "Déverrouiller"
#define T_LOCK "Verrouiller"
#define T_GOTO "Goto"
#define T_PUSHTO "Pushto"
#define T_PUSHINGTO "Pointe vers"
#define T_POSITION "Position"

#define T_SYNC "Synchro"
#define T_SYNCED "Synchro"
#define T_HOUR "Heure"
#define T_HOURS "Heures"
#define T_SYNCEDAT "Synchro à"
#define T_ALIGN "Aligner"
#define T_PC "Ordinateur"
#define T_TRACKING "Suivi"
#define T_TRACKINGOPTIONS "Options du suivi"
#define T_REFRACTION "Refraction"
#define T_ALIGNMENT "Alignement"
#define T_STARTTRACKING "Démarrer le Suivi"
#define T_STOPTRACKING "Arrêter le Suivi"
#define T_TRACKINGSTATE "État du Suivi"
#define T_TRACKINGCORRECTION "Corr. du Suivi"
#define T_NONE "Aucun"
#define T_BOTH "Les deux"
#define T_SIDEOFPIER "Côté du Pilier"
#define T_SETSIDEOFPIER "Déf. Côté du Pilier"
#define T_SAVE "Sauver"
#define T_SAVED "Sauvé"
#define T_SAVING "Sauvegarde"
#define T_Clear "Effacer"
#define T_SPIRAL "Spirale"
#define T_FIELDOFVIEW "Champs Visuel"
#define T_LX200COMMAND "Commande LX200"
#define T_SETVEALUE "Init. Valeur"
#define T_GETVEALUE "Lire Valeur"
#define T_SETTARGET "Init. Objet"
#define T_TARGET "Objet"
#define T_TARGETIS "L'objet est"
#define T_TELESCOPEIS "Le télescope est"
#define T_TELESCOPEEXCEED "Télescope dépasse"
#define T_SENSORLIMIT "Limite capteur"
#define T_DECLIMIT "Limite DEC"
#define T_AZMLIMIT "Limite AZM "
#define T_BELOWHORIZON "Sous l'horizon"
#define T_ABOVEOVERHEAD "Proche du zénith"
#define T_TELESCOPEMOTOR "Moteur Télescope"
#define T_OUTSIDELIMITS "Hors Limites"
#define T_FAULT "Erreur"
#define T_BUSY "Occupé"
#define T_CANTPARK "Parc impossible"
#define T_CANTGOHOME "Home impossible"

#define T_TELESCOPEACTION "Action Télescope"
#define T_SETSPEED "Réglage Vitesse"
#define T_SIDEREAL "Sidéral"
#define T_TIME "Heure"
#define T_SITE "Site"
#define T_SYNCWITHGNSS "Synchro GNSS"
#define T_LUNAR "Lunaire"
#define T_SOLAR "Solaire"
#define T_CLOCK "Horloge"
#define T_TIMEZONE "Fuseau Horaire"
#define T_DATE "Date"
#define T_GNSSTIME "Heure GNSS"
#define T_NOGNSS "Pas de GNSS"
#define T_SIGNAL "Signal"
#define T_DISPLAY "Écran"
#define T_BUTTONSPEED "Vitesse Boutons"

#define T_SUBMODEL "Sous-modèle"
#define T_CONTRAST "Contraste"
#define T_TURNOFF "Éteindre"
#define T_SLEEP "Veille"
#define T_DEEPSLEEP "Sommeil"
#define T_PRESSSHIFTKEY "Appuyez Shift"
#define T_TOTURNON "pour rallumer"
#define T_AFTER "après"
#define T_LOWCONTRAST "Contraste min."
#define T_TURNDISPLAYOFF "Éteindre l'écran"


#define T_SLOW "Lente"
#define T_MEDIUM "Moyenne"
#define T_FAST "Rapide"

#define T_SITEELEVATION "Altitude du Site"
#define T_HORIZON "Horizon"
#define T_HORIZONLIMIT "Limite Horizon"
#define T_OVERHEAD "Zénith"
#define T_OVERHEADLIMIT "Limite Zénith"

#define T_DISPLAYAXIS "Affiche Axes"
#define T_AXIS     "Axes"
#define T_AXIS1MIN "Axe 1 Min."
#define T_AXIS1MAX "Axe 1 Max."
#define T_AXIS2MIN "Axe 2 Min."
#define T_AXIS2MAX "Axe 2 Max."

#define T_MERIDIANE "Méridien Est"
#define T_MERIDIANW "Méridien Ouest"
#define T_MERIDIANLIMIT "Limite Méridien"
#define T_MERIDIANLIMITE "Limite Méridien E"
#define T_MERIDIANLIMITW "Limite Méridien O"
#define T_SELECTSITE "Selection Site"

#define T_MAXHOURANGLE "Angle Horaire Max"
#define T_UNDERPOLE "Sous le Pôle"
#define T_UNDERPOLELIMIT "Sous Limite Pôle"

#define T_FARFROMPOLE "Far From Pole"
#define T_DISTANCE "Distance"

#define T_CURRENTLYTRACKING "Suivi en cours"
#define T_CANNOTBECHANGED "Impossible de changer"
#define T_INITIALISATION "Initialisation"
#define T_THEMOUNTMUSTBEATHOME1 "La monture doit"
#define T_THEMOUNTMUSTBEATHOME2 "être en"
#define T_THEMOUNTMUSTBEATHOME3 "position Maison."
#define T_READYFOR "Prêt pour"
#define T_MOUNTSYNCED "Monture synchro"
#define T_HANDCONTROLLER "Raquette"
#define T_MAINUNITINFO "Info Unité Princip."
#define T_SHOWVERSION "Affichage Version"
#define T_REBOOT "Redémarrage"
#define T_RESETTOFACTORY "Réinit. Usine"
#define T_FIRMWAREVERSION "Version Firmware"
#define T_GERMANEQUATORIAL "Équ. Allemande"
#define T_EQUATORIALFORK "Équ. Fourche"
#define T_ALTAAZIMUTAL "Altaz."
#define T_ALTAAZIMUTALFORK "Altaz. Fourche"

#define T_TURNWIFIOFF "Éteindre la Wifi"
#define T_TURNWIFION "Allumer la Wifi"
#define T_SHOWPASSWORD "Affich. mot de passe"
#define T_SELECTMODE "Sélection Mode"
#define T_SHOWIP "Montre IP"
#define T_PASSWORDIS "Mot de passe:"
#define T_ACCESPOINT "Point d'Accès"
#define T_WIFIINTERFACE "Interface Wifi"

#define T_SUN "Soleil"
#define T_MERCURY "Mercure"
#define T_VENUS "Vénus"
#define T_MARS "Mars"
#define T_JUPITER "Jupiter"
#define T_SATURN "Saturne"
#define T_URANUS "Uranus"
#define T_NEPTUNE "Neptune"
#define T_MOON "Lune"

#define T_CATALOGS "Catalogues"
#define T_SOLARSYSTEM "Système Solaire "
#define T_COORDINATES "Coordonnées"
#define T_USERDEFINED "Déf. par Util."

#define T_FILTER "Filtre"
#define T_FILTERS "Filtres"
#define T_ALLOW "Autoriser"
#define T_ABOVE ">"
#define T_DEG "deg."
#define T_ALL "Toutes"
#define T_FILTERBYCON "Filtre par Const."
#define T_FILTERBYTYPE "Filtre par Type"
#define T_ABOVE_HORIZON "> Horizon"

#define T_RETICULE "Réticule"
#define T_BRIGHTER "plus brillant"
#define T_LESSBRIGHT "moins brillant"
