#pragma once

#define T_N "N"
#define T_S "S"
#define T_E "E"
#define T_W "W"

#define T_NORTH "North"
#define T_SOUTH "South"
#define T_EAST "East"
#define T_WEST "West"

#define T_PRESS_KEY "Press key"
#define T_TO_REBOOT "to reboot"
#define T_WILL_REBOOT "will reboot"
#define T_DEVICE "Device"
#define T_TELESCOPE "Telescope"
#define T_FOCUSER "Focuser"
#define T_MOUNT "Mount"
#define T_MOUNTTYPE "Mount type"
#define T_SELECT_MOUNT "Select Mount"
#define T_POLAR_ALIGNMENT "Polar Alignment"
#define T_TRUE_POLE "True Pole"
#define T_APPARENT_POLE "Apparent Pole"

#define T_ENCODERS "Encoders"
#define T_PULSEPERDEGREE "Pulse per deg"
#define T_AUTO_SYNC "Auto Sync"
#define T_CALIBRATION "Calibration"

#define T_LIMITS "Limits"
#define T_CONNECTED "Connected"
#define T_NOT_CONNECTED "Not Connected"
#define T_TUNKOWN "Unkown"
#define T_ERROR "ERROR"
#define T_STAR "Star"
#define T_STARS "Stars"
#define T_WARNING "WARNING"
#define T_SLEWINGTO "Slewing to" 
#define T_RECENTER "Recenter"
#define T_SELECTASTAR "Select a Star"
#define T_FROMFOLLOWINGLIST "From following list"
#define T_SELECTION "Selection"
#define T_ABORTED "Aborted"
#define T_ALIGNMENT "Alignment"
#define T_FAILED "Failed"
#define T_HASFAILED "has failed"

#define T_SPEED "Speed"
#define T_GUIDESPEED "Guiding Speed"
#define T_DEFAULTSPEED "Default Speed"
#define T_DRIFTSPEED "Drift Speed"
#define T_FASTSPEED "Fast Speed"
#define T_MEDIUMSPEED "Medium Speed"
#define T_SLOWSPEED "Slow Speed"
#define T_MAXSPEED "Max Speed"
#define T_GUIDE "Guiding"
#define T_FAST "Fast"
#define T_MEDIUM "Medium"
#define T_SLOW "Slow"
#define T_MAX "Max"

#define T_START "Start"
#define T_STARTED "Started"
#define T_STOP "Stop"
#define T_CANCEL "Cancel"
#define T_CANCELED "Canceled"
#define T_COMPLETE "Complete"
#define T_WRONG "Wrong"
#define T_NOTDEFINED "not defined"
#define T_SUCESS "Success"
#define T_STARADDED "Star added"
#define T_VERSION "version"
#define T_YES "YES"
#define T_NO "NO"
#define T_ON "ON"
#define T_OFF "OFF"
#define T_RESET "Reset"
#define T_VALUE "Value"
#define T_SET "Set"
#define T_GET "Get"
#define T_DONE "Done"
#define T_TO "To"
#define T_LOW "Low"
#define T_HIGH "High"
#define T_MIN "Min"
#define T_MAX "Max"
#define T_ERGONOMICS "Ergonomics"
#define T_RIGHT_HANDER "right-hander"
#define T_LEFT_HANDER "left-hander"
#define T_FACTORY "Factory"
#define T_DIRECT "Direct"
#define T_REVERSE "Reverse"
#define T_REVERSEDROTATION "Reversed Rotation"
#define T_DIRECTROTATION "Direct Rotation"
#define T_CONFIG "Config"
#define T_ROTATION "Rotation"
#define T_BACKLASH "Backlash"
#define T_BACKLASHSPEED "Backlash Speed"
#define T_GEAR "Gear"
#define T_RATIO "Ratio"
#define T_MICROSTEP "MicroStep"
#define T_INSECONDS "in seconds"
#define T_MOTOR "Motor"
#define T_STEPPER "Stepper"
#define T_STEPS "Steps"
#define T_RESOLUTION "Resolution"
#define T_INCREMENTATION "Incrementation"
#define T_STEPSPERROT "Steps per Rot."
#define T_LOWCURR "Low Curr."
#define T_HIGHCURR "High Curr."
#define T_CURRENT "Current"
#define T_PEAK "peak"
#define T_MaxSlew "Max Slew"
#define T_Config "Config"
#define T_TIMESETTINGS "Time Settings"
#define T_TELESCOPESETTINGS "Telescope Settings"
#define T_SHCSETTINGS "SHC Settings"
#define T_SLEWSETTING "Slew Settings"
#define T_MOTORSETTINGS "Motor %u Settings"
#define T_SHOWSETTINGS "Show Settings"
#define T_FOCUSERSETTINGS "Focuser Settings"
#define T_DISPLAYSETTINGS "Display Settings"
#define T_FOCUSERINFO "Focuser Info"

#define T_ACCELERATION "Acceleration"

#define T_LATITUDE "Latitude"
#define T_LONGITUDE "Longitude"
#define T_AZIMUTH "Azimuth"
#define T_ALTITUDE "Altitude"
#define T_DECLINAISON "Declination"
#define T_RIGHTASC "Right Asc."
#define T_LOCALTIME "Local Time"
#define T_DEGREE "degree"

#define T_PARKPOSITION "Park Position"
#define T_MAXPOSITION "Max Position"
#define T_MAXPOSITION2 "Max  Pos."
#define T_STARTPOSITION2 "Start Pos."

#define T_GOTOPOSITION "Goto Position"
#define T_SYNCPOSITION "Sync Position"
#define T_MANUALSPEED "Manual Speed"
#define T_MANUALSPEED2 "Man. Speed"
#define T_GOTOSPEED "Goto Speed"
#define T_GOTOSPEED2 "Goto Speed"
#define T_ACCFORMAN "Acc. for Man."
#define T_ACCFORMAN2 "Acc. man."
#define T_ACCFORGOTO "Acc. for Goto"
#define T_ACCFORGOTO2 "Acc. cmd."
#define T_DECFORMAN "Dec. for Man."
#define T_DECFORMAN2 "Dec. man."

#define T_UNPARK "Unpark"
#define T_PARK "Park"
#define T_FLIP "Flip"
#define T_HOME "Home"
#define T_PARKED "Parked"
#define T_NOOBJECT "No Object"
#define T_SELECTED "Selected"
#define T_FOCUSERACTION "Focuser Action"

#define T_PARKANDHOME "Park & Home"
#define T_SETPARK "Set Park"
#define T_SETHOME "Set Home"
#define T_RESETHOME "Reset Home"

#define T_ATHOME "at Home"
#define T_UNLOCK "Unlock"
#define T_LOCK "Lock"
#define T_GOTO "Goto"
#define T_PUSHTO "Pushto"
#define T_PUSHINGTO "Pushing to"
#define T_POSITION "Position"

#define T_SYNC "Sync"
#define T_SYNCED "Synced"
#define T_HOUR "Hour"
#define T_HOURS "Hours"
#define T_SYNCEDAT "Synced at"
#define T_ALIGN "Align"
#define T_PC "PC"
#define T_TRACKING "Tracking"
#define T_TRACKINGOPTIONS "Tracking Options"
#define T_REFRACTION "Refraction"
#define T_ALIGNMENT "Alignment"
#define T_STARTTRACKING "Start Tracking"
#define T_STOPTRACKING "Stop Tracking"
#define T_TRACKINGSTATE "Tracking State"
#define T_TRACKINGCORRECTION "Tracking Corr."
#define T_NONE "None"
#define T_BOTH "Both"
#define T_SIDEOFPIER "Side of Pier"
#define T_SETSIDEOFPIER "Set Side of Pier"
#define T_SAVE "Save"
#define T_SAVED "Saved"
#define T_SAVING "Saving"
#define T_Clear "Clear"
#define T_SPIRAL "Spiral"
#define T_FIELDOFVIEW "Field of view"
#define T_LX200COMMAND "LX200 Command"
#define T_SETVEALUE "Set Value"
#define T_GETVEALUE "Get Value"
#define T_SETTARGET "Set Target"
#define T_TARGET "Target"
#define T_TARGETIS "Target is"
#define T_TELESCOPEIS "Telescope is"
#define T_TELESCOPEEXCEED "Telescope exceed"
#define T_SENSORLIMIT "Sensor limit"
#define T_DECLIMIT "DEC limit"
#define T_AZMLIMIT "AZM limit"
#define T_BELOWHORIZON "Below Horizon"
#define T_ABOVEOVERHEAD "Close to Zenith"
#define T_TELESCOPEMOTOR "Telescope Motor"
#define T_OUTSIDELIMITS "Outside Limits"
#define T_FAULT "Fault"
#define T_BUSY "Busy"
#define T_CANTPARK "Can't Park"
#define T_CANTGOHOME "Can't go Home"

#define T_TELESCOPEACTION "Telescope Action"
#define T_SETSPEED "Set Speed"
#define T_SIDEREAL "Sidereal"
#define T_TIME "Time"
#define T_SITE "Site"
#define T_SYNCWITHGNSS "Sync to GNSS"
#define T_LUNAR "Lunar"
#define T_SOLAR "Solar"
#define T_CLOCK "Clock"
#define T_TIMEZONE "Time Zone"
#define T_DATE "Date"
#define T_GNSSTIME "GNSS Time"
#define T_NOGNSS "NO GNSS"
#define T_SIGNAL "Signal"
#define T_DISPLAY "Display"
#define T_BUTTONSPEED "Button Speed"

#define T_SUBMODEL "Submodel"
#define T_CONTRAST "Contrast"
#define T_TURNOFF "Turn Off"
#define T_SLEEP "Sleep"
#define T_DEEPSLEEP "DeepSleep"
#define T_PRESSSHIFTKEY "Press Shift Key"
#define T_TOTURNON "to turn on"
#define T_AFTER "after"
#define T_LOWCONTRAST "Low Contrast"
#define T_TURNDISPLAYOFF "Turn display off"

#define T_BUTTONSPEED "Button Speed"
#define T_SLOW "Slow"
#define T_MEDIUM "Medium"
#define T_FAST "Fast"

#define T_SITEELEVATION "Site Elevation"
#define T_HORIZON "Horizon"
#define T_HORIZONLIMIT "Horizon Limit"
#define T_OVERHEAD "Overhead"

#define T_DISPLAYAXIS "Display Axis"
#define T_AXIS     "Axis"
#define T_AXIS1MIN "Axis1 Min."
#define T_AXIS1MAX "Axis1 Max."
#define T_AXIS2MIN "Axis2 Min."
#define T_AXIS2MAX "Axis2 Max."

#define T_OVERHEADLIMIT "Overhead Limit"
#define T_MERIDIANE "Meridian E"
#define T_MERIDIANW "Meridian W"
#define T_MERIDIANLIMIT "Meridian Limit"
#define T_MERIDIANLIMITE "Meridian Limit E"
#define T_MERIDIANLIMITW "Meridian Limit W"
#define T_SELECTSITE "Select Site"

#define T_MAXHOURANGLE "Max Hour Angle"
#define T_UNDERPOLE "Under Pole"
#define T_UNDERPOLELIMIT "Under Pole Limit"

#define T_FARFROMPOLE "Far From Pole"
#define T_DISTANCE "Distance"

#define T_CURRENTLYTRACKING "currently Tracking"
#define T_CANNOTBECHANGED "cannot be changed"
#define T_INITIALISATION "Initilisation"
#define T_THEMOUNTMUSTBEATHOME1 "The mount must"
#define T_THEMOUNTMUSTBEATHOME2 "be set at"
#define T_THEMOUNTMUSTBEATHOME3 "home position."
#define T_READYFOR "Ready for"
#define T_MOUNTSYNCED "Mount Synced"
#define T_HANDCONTROLLER "Hand Controller"
#define T_MAINUNITINFO "Main Unit Info"
#define T_SHOWVERSION "Show Version"
#define T_REBOOT "Reboot"
#define T_RESETTOFACTORY "Reset to Factory"
#define T_FIRMWAREVERSION "Firmware Version"
#define T_GERMANEQUATORIAL "German Equatorial"
#define T_EQUATORIALFORK "Equatorial Fork"
#define T_ALTAAZIMUTAL "Altazimutal"
#define T_ALTAAZIMUTALFORK "Altazimutal Fork"

#define T_TURNWIFIOFF "Turn Wifi off"
#define T_TURNWIFION "Turn Wifi on"
#define T_SHOWPASSWORD "Show Password"
#define T_SELECTMODE "Select Mode"
#define T_SHOWIP "Show IP"
#define T_PASSWORDIS "Password is"
#define T_ACCESPOINT "Access Point"
#define T_WIFIINTERFACE "Wifi Interface"

#define T_SUN "Sun"
#define T_MERCURY "Mercury"
#define T_VENUS "Venus"
#define T_MARS "Mars"
#define T_JUPITER "Jupiter"
#define T_SATURN "Saturn"
#define T_URANUS "Uranus"
#define T_NEPTUNE "Neptune"
#define T_MOON "Moon"

#define T_CATALOGS "Catalogs"
#define T_SOLARSYSTEM "Solar System"
#define T_COORDINATES "Coordinates"
#define T_USERDEFINED "User Defined"

#define T_FILTER "Filter"
#define T_FILTERS "Filters"
#define T_ALLOW "Allow"
#define T_ABOVE "Above"
#define T_DEG "deg."
#define T_ALL "All"
#define T_FILTERBYCON "Filter by Con"
#define T_FILTERBYTYPE "Filter by Type"
#define T_ABOVE_HORIZON "Above Horizon"

#define T_RETICULE "Reticule"
#define T_BRIGHTER "Brighter"
#define T_LESSBRIGHT "Less Bright"
